VENDOR: Ensure dbus/transport_unix.go implements the SendNullByte method
  ---> Making bundle: binary (in bundles/17.05.0-ce/binary)
  Building: bundles/17.05.0-ce/binary-client/docker-17.05.0-ce
  Created binary: bundles/17.05.0-ce/binary-client/docker-17.05.0-ce
  Building: bundles/17.05.0-ce/binary-daemon/dockerd-17.05.0-ce
  # github.com/docker/docker/libcontainerd
  .gopath/src/github.com/docker/docker/libcontainerd/client.go:13: undefined: container
  .gopath/src/github.com/docker/docker/libcontainerd/types.go:32: undefined: StateInfo
  # github.com/docker/docker/vendor/github.com/godbus/dbus
  .gopath/src/github.com/docker/docker/vendor/github.com/godbus/dbus/transport_unix.go:51: cannot use t (type *unixTransport) as type transport in return argument:
          *unixTransport does not implement transport (missing SendNullByte method)
  .gopath/src/github.com/docker/docker/vendor/github.com/godbus/dbus/transport_unix.go:57: cannot use t (type *unixTransport) as type transport in return argument:
          *unixTransport does not implement transport (missing SendNullByte method)

Signed-off-by: R Tyler Croy <tyler@monkeypox.org>